export default {
	SEND_STORAGE_ITEMS_REQUEST: 'SEND_STORAGE_ITEMS_REQUEST',
	RECEIVE_STORAGE_ITEMS_SUCCESS: 'RECEIVE_STORAGE_ITEMS_SUCCESS',
	RECEIVE_STORAGE_ITEMS_ERROR: 'RECEIVE_STORAGE_ITEMS_ERROR',
	SET_STORAGE_ITEM: 'SET_STORAGE_ITEM',
	SET_STORAGE_ITEM_SUCCESS: 'SET_STORAGE_ITEM_SUCCESS',
	SET_STORAGE_ITEM_ERROR: 'SET_STORAGE_ITEM_ERROR'
};