export default {
	SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
	SELECT_SEARCH_RESULT: 'SELECT_SEARCH_RESULT',
	SEND_SEARCH_REQUEST: 'SEND_SEARCH_REQUEST',
	RECEIVE_SEARCH_SUCCESS: 'RECEIVE_SEARCH_SUCCESS',
	RECEIVE_SEARCH_ERROR: 'RECEIVE_SEARCH_ERROR'
};