export default {
	SET_AUTH_NICK: 'SET_AUTH_NICK',
	SET_AUTH_PWD: 'SET_AUTH_PWD',
	SET_AUTH_SAVE_CREDS: 'SET_AUTH_SAVE_CREDS',
	LOGIN: 'LOGIN',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_ERROR: 'LOGIN_ERROR',
	LOGIN_SILENTLY: 'LOGIN_SILENTLY',
	LOGIN_SILENTLY_SUCCESS: 'LOGIN_SILENTLY_SUCCESS',
	LOGIN_SILENTLY_ERROR: 'LOGIN_SILENTLY_ERROR'
};