export default {
	SET_AUTH_NICK: 'SET_AUTH_NICK',
	SET_AUTH_PWD: 'SET_AUTH_PWD',
	SEND_AUTH_REQUEST: 'SEND_AUTH_REQUEST',
	RECEIVE_AUTH_SUCCESS: 'RECEIVE_AUTH_SUCCESS',
	RECEIVE_AUTH_ERROR: 'RECEIVE_AUTH_ERROR'
};