export default {
	SET_LOGIN_NICK: 'SET_LOGIN_NICK',
	SET_LOGIN_PWD: 'SET_LOGIN_PWD',
	SEND_LOGIN_REQUEST: 'SEND_LOGIN_REQUEST',
	RECEIVE_LOGIN_SUCCESS: 'RECEIVE_LOGIN_SUCCESS',
	RECEIVE_LOGIN_ERROR: 'RECEIVE_LOGIN_ERROR'
};